module.exports = {
  VIOLATION_TYPE: {
    DAILY_LOSS: 'DAILY_LOSS',
    POSITION_SIZE: 'POSITION_SIZE',
    MAX_POSITIONS: 'MAX_POSITIONS',
    CIRCUIT_BREAKER: 'CIRCUIT_BREAKER',
    KILL_SWITCH: 'KILL_SWITCH',
  },
  
  RISK_ACTION: {
    BLOCK: 'BLOCK',
    ALERT: 'ALERT',
    LIQUIDATE: 'LIQUIDATE',
  },
  
  LIMIT_TYPE: {
    DAILY_LOSS: 'DAILY_LOSS',
    POSITION_SIZE: 'POSITION_SIZE',
    MAX_POSITIONS: 'MAX_POSITIONS',
    MAX_DRAWDOWN: 'MAX_DRAWDOWN',
  },
};