module.exports = {
  FLAG_TYPE: {
    KILL_SWITCH: 'KILL_SWITCH',
    MAINTENANCE: 'MAINTENANCE',
    CIRCUIT_BREAKER: 'CIRCUIT_BREAKER',
  },
  
  AUDIT_EVENT: {
    USER_LOGIN: 'USER_LOGIN',
    USER_LOGOUT: 'USER_LOGOUT',
    SIGNAL_RECEIVED: 'SIGNAL_RECEIVED',
    TRADE_INTENT_CREATED: 'TRADE_INTENT_CREATED',
    ORDER_PLACED: 'ORDER_PLACED',
    ORDER_CANCELLED: 'ORDER_CANCELLED',
    RISK_VIOLATION: 'RISK_VIOLATION',
    KILL_SWITCH_TRIGGERED: 'KILL_SWITCH_TRIGGERED',
    KILL_SWITCH_DISABLED: 'KILL_SWITCH_DISABLED',
    POSITIONS_SQUARED_OFF: 'POSITIONS_SQUARED_OFF',
    CONFIG_CHANGED: 'CONFIG_CHANGED',
  },
  
  USER_ROLE: {
    ADMIN: 'ADMIN',
    TRADER: 'TRADER',
    VIEWER: 'VIEWER',
  },
  
  ACCOUNT_STATUS: {
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
    SUSPENDED: 'SUSPENDED',
  },
};